# Generated by Django 2.2 on 2021-05-25 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(to='account.Role', verbose_name='Роли пользователя'),
        ),
    ]
