# Generated by Django 2.0 on 2021-05-20 14:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='moderator_for',
        ),
        migrations.AddField(
            model_name='company',
            name='moderator_for',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Модератор для организации'),
        ),
        migrations.AlterField(
            model_name='useraccesslevel',
            name='access_level',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.AccessLevel', verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='useraccesslevel',
            name='section',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Section', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='useraccesslevel',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='account.Profile', verbose_name='Пользователь'),
        ),
    ]
