# Generated by Django 2.0 on 2021-05-20 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210520_2239'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccesslevel',
            name='access_level',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.AccessLevel', verbose_name='Уровень доступа'),
        ),
        migrations.AlterField(
            model_name='useraccesslevel',
            name='section',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Section', verbose_name='Раздел'),
        ),
        migrations.AlterField(
            model_name='useraccesslevel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile', verbose_name='Пользователь'),
        ),
    ]
