# Generated by Django 2.2 on 2021-05-25 13:25

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('account', '0002_profile_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='moderator',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Модератор'),
        ),
    ]
