# Generated by Django 2.2.20 on 2021-05-25 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_auto_20210525_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='accesslevel_section_role',
            name='access_level',
            field=models.IntegerField(choices=[(1, 'Read (R)'), (2, 'Insert (I)'), (3, 'Update (U)'), (4, 'Delete (D)'), (5, 'Execute (E)')], default=1, verbose_name='Уровень досутпа'),
        ),
    ]
