# Generated by Django 2.2.20 on 2021-05-27 03:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='AccessLevel_Section_User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.IntegerField(choices=[(1, 'Read (R)'), (2, 'Insert (I)'), (3, 'Update (U)'), (4, 'Delete (D)'), (5, 'Execute (E)')], default=1, verbose_name='Уровень досутпа')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Section', verbose_name='Раздел')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Profile', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'уровень доступа для раздела(для пользователя)',
                'verbose_name_plural': 'уровни доступа для раздела(для пользователя)',
                'ordering': ['section'],
            },
        ),
        migrations.CreateModel(
            name='AccessLevel_Section_Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_level', models.IntegerField(choices=[(1, 'Read (R)'), (2, 'Insert (I)'), (3, 'Update (U)'), (4, 'Delete (D)'), (5, 'Execute (E)')], default=1, verbose_name='Уровень досутпа')),
                ('role', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='account.Role', verbose_name='Роль')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.Section', verbose_name='Раздел')),
            ],
            options={
                'verbose_name': 'уровень доступа для раздела(для роли)',
                'verbose_name_plural': 'уровни доступа для раздела(для роли)',
                'ordering': ['section'],
            },
        ),
    ]
