# Generated by Django 2.2.20 on 2021-05-27 05:37

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_accesslevel_section_role_accesslevel_section_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='organization_id',
            field=models.CharField(default=uuid.UUID('fe0ea4d5-f1d9-4b84-b348-d2c24ec0efee'), max_length=126, verbose_name='ID организации'),
        ),
    ]
