# Generated by Django 2.2.20 on 2021-05-27 06:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_company_organization_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='organization_id',
            field=models.CharField(default=uuid.UUID('3a69f613-e775-4a3a-a723-cb57a26ce3a7'), max_length=126, verbose_name='ID организации'),
        ),
        migrations.AlterField(
            model_name='profile',
            name='roles',
            field=models.ManyToManyField(blank=True, to='account.Role', verbose_name='Роли пользователя'),
        ),
    ]
